### ISSUE TITLE
Opening a 3Speak Video in the 3Speak App from the 'open in App'  button at 3Speak.tv result in JavaScript Error

### ISSUE THREAD

**Issue by edje42** [3speaknetwork/3Speak-app#12]
When I open a 3Speak Video in the 3Speak.tv service using the button 'Open in Desktop App', I receive an error when my 3Speak Desktop App is not running. The process opens a new window in my browser, asking if I want to open in the Desktop App. When I hit the button to continue to open in Desktop App, it actually opens the Desktop App, but also shows the error.

When I test the same with my 3Speak Desktop App already open, all works great. Meaning, the video is opened in the Desktop App and I can play it.

![Screenshot 2021-06-20 at 11 09 45](https://user-images.githubusercontent.com/33900093/122668983-5fb94900-d1bb-11eb-942b-51fae69316e7.png)

**Comment by vaultec81** [comment]
No response from author and haven't had any complaints what so ever. Closing
